DROP TABLE IF EXISTS Message;
DROP TABLE IF EXISTS SourceMessage;
DROP TABLE IF EXISTS Languages;


CREATE TABLE Languages(
  lang VARCHAR(32) NOT NULL COMMENT 'аббревиатура языка',
  name VARCHAR(35) DEFAULT NULL COMMENT 'название языка',
  PRIMARY KEY (lang)
)
ENGINE = INNODB AVG_ROW_LENGTH = 8192 CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE SourceMessage(
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT 'счетчик записей',
  category VARCHAR(32) DEFAULT 'rec' COMMENT 'категория',
  message TEXT DEFAULT NULL COMMENT 'оригинал сообщения',
  PRIMARY KEY (id)
)
ENGINE = INNODB AVG_ROW_LENGTH = 92 CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE Message(
  id INT(11) NOT NULL COMMENT 'для связи с оригиналами сообщений',
  language VARCHAR(32) NOT NULL COMMENT 'аббревиатура языка',
  translation TEXT DEFAULT NULL COMMENT 'перевод сообщения',
  PRIMARY KEY (id, language),
  CONSTRAINT FK_Message_Languages FOREIGN KEY (language)
  REFERENCES Languages (lang) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT FK_Message_SourceMessage FOREIGN KEY (id)
  REFERENCES SourceMessage (id) ON DELETE CASCADE ON UPDATE RESTRICT
)
ENGINE = INNODB AVG_ROW_LENGTH = 180 CHARACTER SET utf8 COLLATE utf8_general_ci;


INSERT INTO `Languages` (`lang`, `name`) VALUES
('ru', 'Russian');


INSERT INTO SourceMessage (message) VALUES
('Settings'),
('select country'),
('Hello!'),
('Your account is activated, the system set up an office for you, as you are subscribed to the mailing list of all the news system'),
('To go to the office, follow the link'),
('enter'),
('Login'),
('and enter your login information'),
('login'),
('password'),
('In order to proceedfollow the link'),
('Do not remove this message until you finally registered.'),
('This link is unique and will operate until you pass all registration steps'),
('Best Regards'),
('administration'),
('Congratulations on your purchase Business Start! Registration is fully passed.'),
('Now login information will be used only your email and password.'),
('To confirm registration follow the link'),
('Model Name'),
('Lable field name'),
('Empty item name'),
('Profile model relation name'),
('Participants'),
('Unified database participants'),
('Participants structure'),
('BusinessClub structure'),
('Domain'),
('Tariff'),
('Created'),
('Firstname'),
('Lastname'),
('City'),
('Country'),
('Structure'),
('Business Club'),
('Referal'),
('Checks'),
('Time'),
('Phone'),
('Skype'),
('Birthday'),
('Gmt'),
('Income'),
('Transfer to the Fund'),
('Activate'),
('Deactivate'),
('Blacklist'),
('See structure'),
('New Participant'),
('Registration'),
('Register'),
('Logout'),
('username'),
('username or email'),
('Remember me next time'),
('Username is incorrect.'),
('Email is incorrect.'),
('This user''s name already exists.'),
("This user's email address already exists."),
('You registered from {site_name}'),
('Please activate you account go to {activation_url}'),
('You account is not activated.'),
('You account is blocked.'),
('Password is incorrect.'),
('E-mail'),
('Verification Code'),
('Old Password'),
('Old Password is incorrect.'),
('Retype Password'),
('Retype Password is incorrect.'),
('Incorrect password (minimal length 4 symbols).'),
('Incorrect username (length between 3 and 20 characters).'),
('Incorrect symbols (A-z0-9).'),
('Variable name may consist of a-z, 0-9, underscores, begin with a letter.'),
('Length of '' + n + '' must be between ''+min+'' and ''+max+''.'),
('Please enter the letters as they are shown in the image above.'),
('Letters are not case-sensitive.'),
('Minimal password length 4 symbols.'),
('Lost Password?'),
('Profile'),
('activation key'),
('User activation'),
('You account is active.'),
('You account is activated.'),
('Incorrect activation URL.'),
('Registration date'),
('Last visit'),
('Superuser'),
('Status'),
('Roles'),
('Ok'),
('Show all'),
('Save'),
('Cancel'),
('New password is saved.'),
('Change password'),
('Your profile'),
('Thank you for your registration. Please check your email or login.'),
('Thank you for your registration. Please check your email.'),
('Please check your email. An instructions was sent to your email address.'),
('Thank you for your registration. Please {{login}}.'),
('Thank you for your registration. Contact Admin to activate your account.'),
('Restore'),
('Please enter your login or email addres.'),
('Incorrect recovery link.'),
('Already exists.'),
('First Name'),
('Last Name'),
('Email'),
('Create System User'),
('System Users'),
('No'),
('Yes'),
('Yes and show on registration form'),
('No, but show on registration form'),
('Not active'),
('Active'),
('Superadmin'),
('Admin'),
('Moderator'),
('Without Role'),
('Manage System Users'),
('Update System User'),
('View System User'),
('Banned'),
('Please fill out the following form with your login credentials:'),
('Fields with * are required'),
('List User'),
('Edit'),
('Edit profile'),
('Create User'),
('Create'),
('Manage'),
('Manage Users'),
('Users'),
('Update User'),
('Delete User'),
('Delete file'),
('View User'),
('Are you sure to delete this item?'),
('Changes is saved.'),
('Manage Profile Field'),
('Variable name'),
('Title'),
('Field Type'),
('Field Size'),
('Field Size min'),
('Required'),
('Match'),
('Range'),
('Error Message'),
('Other Validator'),
('JSON string (example: {example}).'),
('Default'),
('Position'),
('Visible'),
('Registered users'),
('For all'),
('Only owner'),
('Hidden'),
('Profile Fields'),
('View Profile Field #'),
('Manage Profile Fields'),
('Create Profile Field'),
('List Profile Field'),
('View Profile Field'),
('Delete Profile Field'),
('Update Profile Field'),
('Widget'),
('Widget parametrs'),
('Widget name.'),
('Allowed lowercase letters and digits.'),
('Field name on the language of "sourceLanguage".'),
('Field type column in the database.'),
('Field size column in the database.'),
('The minimum value of the field (form validator).'),
('Required field (form validator).'),
('Regular expression (example: ''/^[A-Za-z0-9\s,]+$/u'').'),
('Predefined values (example: 1;2;3;4;5 or 1==One;2==Two;3==Three;4==Four;5==Five).'),
('Error message when you validate the form.'),
('The value of the default field (database).'),
('Display order of fields.'),
('Not visited'),
('Search'),
('Advanced Search'),
('You may optionally enter a comparison operator ( <, <=, >, >=, <> or = ) at the beginning of each of your search values to specify how the comparison should be done.'),
('Photo'),
('select city'),
('OPPORTUNITIES'),
('RULES'),
('QUESTIONS AND ANSWERS'),
('LOGIN'),
('Next'),
('NEW MEMBER REGISTRATION'),
('STEP'),
('Static Pages'),
('CURRENT'),
('REGISTRATIONS'),
('Exit'),
('STATISTICS'),
('STRUCTURE'),
('NEWS'),
('CHAT'),
('INVITATION'),
('SETTINGS'),
('HELP'),
('SIGN UP'),
('Live'),
('News'),
('Feedback'),
('YouTube Channel'),
('About Us'),
('About the project'),
('Our partners'),
('Contact and Bank details'),
('Service'),
('Financial assistance'),
('Business Machine'),
('Joint advertising'),
('Personal Website'),
('SMS-mailing'),
('Rules'),
('Participation agreement'),
('Community Guidelines'),
('Anti-spam policy'),
('Cooperation'),
('Payment systems'),
('Exchangers'),
('Advertising platforms'),
('Become a Reseller'),
('Support service'),
('Instructions'),
('Forum'),
('Contact us'),
('World Charity System JMWS LLC POLAND'),
('PERSONAL TEAM STRUCTURE'),
('GLOBAL STRUCTURE OF BUSINESS CLUB'),
('Data saved successfull'),
('Finance'),
('Offers'),
('Site work'),
('Add banners to admin panel.'),
('DOWNLOAD'),
('INTERNET ADVERTISING'),
('Width:'),
('Height:'),
('ACCOUNT SETTINGS'),
('USERNAME'),
('NAME'),
('SURNAME'),
('DATE OF BIRTH'),
('CITY'),
('COUNTRY'),
('allow to show to all users'),
('VIBER / MOBILE'),
('CURRENT PASSWORD'),
('NEW PASSWORD'),
('NEW PURSE'),
('MY TIME'),
('LANGUAGE'),
('RUSSIAN'),
('RUSSIAN2'),
('YOUR PURSE'),
('PAYMENT DETAILS'),
('AVATAR'),
('SELECT IMAGE'),
('show country to everyone user'),
('show city to everyone user'),
('show skype to everyone user'),
('show email to everyone user'),
('All fields except your profile skype and social networks are required'),
('The selected name of your account will be reserved for you until it is activated'),
('But even up to 30 days after deactivation, yours choosen name will be fixed'),
('SAVE'),
('Your e-mail has been changed to'),
('Thank you! You just confirmed your email address. CONTINUE passed all 4 steps.'),
('NEXT'),
('On your mail has been sent. In the letter you will find a link Click on it.'),
('IF YOU DO NOT RECEIVE A LETTER'),
('Congratulations! You became a full member of the system.'),
('To activate your account, you must make the participation fee of $'),
('ou will pass on website payment system to pay'),
('PAY $'),
('I agree with the rules and accept'),
('Terms and conditions'),
('Congratulations! You are already logged in!'),
('Now, to become a party to a business, you must pass the final step.'),
('Business participation will allow you to get so many things and so many things! Do not waste time!'),
('REGISTERED MEMBERS'),
('CURRENT REGISTRATION'),
('Error'),
('JOIN'),
('LEADERS'),
('FEE PAID'),
('CURRENT PAYMENTS'),
('GIVEN ON CHARITY'),
('CURRENT fEES'),
('ENTER THE CODE'),
('FORGOT YOUR PASSWORD?'),
('PASSWORD'),
('Information'),
('Add user to list'),
('Send message'),
('Find users'),
('The User was added to list'),
('You can''t add yourself'),
('The User has already been added'),
('The User has been added successfuly'),
('The User hasn''t been found'),
('The User hasn''t been added'),
('Recipient''s or Sender''s purse absent'),
('Chat'),
('Cities'),
('General statistics'),
('Total'),
('Today'),
('Entered'),
('Money Turnover'),
('Activations total'),
('Activations today'),
('Capital total'),
('Capital today'),
('Charity'),
('Total transferred'),
('Visits'),
('Yesterday'),
('Month'),
('month'),
('day'),
('hour'),
('from'),
('step'),
('to'),
('send'),
('invalid interval date format'),
('No data for display'),
('Mpversions'),
('Faq Management'),
('Add'),
('Invitation'),
('Id'),
('Video Link'),
('File'),
('File Link'),
('Create Invitation'),
('Update Invitation'),
('View Invitation'),
('Manage Invitations'),
('Marketings Plan'),
('set current'),
('Manage versions of marketings plan'),
('Description'),
('Creationdate'),
('Activity'),
('Create Version'),
('View Mpversions'),
('#'),
('List Mpversions'),
('Create Mpversions'),
('Update Mpversions'),
('Delete Mpversions'),
('Manage Mpversions'),
('Operations'),
('name'),
('value'),
('Delete'),
('Create News'),
('Manage News'),
('Requisites'),
('Training'),
('Language Management'),
('<br>Empty password field means the old password<br>fill it only if you want to change old password.<br><br>'),
('Missing Languages'),
('Language sign'),
('This Language allredy present'),
('New Language added successfull'),
('Language deleted successfull'),
('Edition completed'),
('Wrong edition, has error'),
('Russian'),
('Common Statistics'),
('Countries'),
('Update News'),
('List News'),
('View News'),
('Activated'),
('Upload Illustration'),
('Content'),
('Create Training'),
('Manage Trainings'),
('Image'),
('Number'),
('Date'),
('Manage FAQ'),
('Financial Mail'),
('Performance Mail'),
('Offer Mail'),
('Question'),
('Answer'),
('Category'),
('List FAQ'),
('Create FAQ'),
('Update Training'),
('FAQ'),
('Banner'),
('Text'),
('Create Countries'),
('Manage Countries'),
('Name'),
('Code'),
('Code Num'),
('Phone Code'),
('List Countries'),
('Index Management'),
('Manage Cities'),
('Create Cities'),
('Version id'),
('Sliderlist'),
('leader'),
('Descriptio'),
('price of activation'),
('price of start'),
('accural purse A'),
('random to one B1'),
('random to one B2'),
('random to one B3'),
('accural purse F');



INSERT INTO `Message` (`id`, `language`, `translation`) VALUES
(1, 'ru', 'Настройки'),
(2, 'ru', 'Выбрать страну'),
(3, 'ru', 'Здравствуйте!'),
(4, 'ru', 'Ваш аккаунт активирован, в системе создан офис для Вас, также Вы подписаны на почтовую рассылку всех новостей системы'),
(5, 'ru', 'Чтобы зайти в офис, следуйте по ссылке'),
(6, 'ru', 'Войти'),
(7, 'ru', 'Вход'),
(8, 'ru', 'и введите информацию'),
(9, 'ru', 'логин'),
(10, 'ru', 'пароль'),
(11, 'ru', 'Для того чтобы перейти по ссылке'),
(12, 'ru', 'Не удаляйте это сообщение до завершения вашей регистрации'),
(13, 'ru', 'Эта ссылка является уникальной и будет работать, пока вы проходите все этапы регистрации'),
(14, 'ru', 'С наилучшими пожеланиями'),
(15, 'ru', 'администрация сайта'),
(16, 'ru', 'Поздравляем с покупкой Бизнес-Старта! Регистрация полностью пройдена.'),
(17, 'ru', 'Теперь для входа будут использованы исключительно ваши емейл и пароль.'),
(18, 'ru', 'Для подтверждения регистрации перейдите по ссылке'),
(19, 'ru', 'Имя модели'),
(20, 'ru', 'Имя поля'),
(21, 'ru', 'Пустое поле Имя'),
(22, 'ru', 'отношение'),
(23, 'ru', 'Участники'),
(24, 'ru', 'Единая база участников'),
(25, 'ru', 'Структура участников'),
(26, 'ru', 'Структура бизнесклуба'),
(27, 'ru', 'Домен'),
(28, 'ru', 'Статус'),
(29, 'ru', 'Создано'),
(30, 'ru', 'Имя'),
(31, 'ru', 'Фамилия'),
(32, 'ru', 'Город'),
(33, 'ru', 'Страна'),
(34, 'ru', 'Структура'),
(35, 'ru', 'Бизнесс клуб'),
(36, 'ru', 'Пригласивший'),
(37, 'ru', 'Чеки'),
(38, 'ru', 'Время'),
(39, 'ru', 'Телефон'),
(40, 'ru', 'Скайп'),
(41, 'ru', 'День рождения'),
(42, 'ru', 'Время по Гринвичу'),
(43, 'ru', 'Доход'),
(44, 'ru', 'Отчисления'),
(45, 'ru', 'Запустить'),
(46, 'ru', 'Заблокировать'),
(47, 'ru', 'Черный список'),
(48, 'ru', 'Посмотреть структуру'),
(49, 'ru', 'Новый участник'),
(50, 'ru', 'Регистрация'),
(51, 'ru', 'Зарегистрироваться'),
(52, 'ru', 'Выйти'),
(53, 'ru', 'пользователь'),
(54, 'ru', 'пользователь или e-mail'),
(55, 'ru', 'Запомнить меня'),
(56, 'ru', 'Имя пользователя указано неверно'),
(57, 'ru', 'E-mail указан неверно'),
(58, 'ru', 'Пользователь с таким именем уже зарегистрирован'),
(59, 'ru', 'Адрес электронной почты уже существует'),
(60, 'ru', 'Вы зарегистрировались на сайте {site_name}'),
(61, 'ru', 'Для активации аккаунта пожалуйста перейдите по следующей ссылке {activation_url}'),
(62, 'ru', 'Ваш аккаунт не активирован.'),
(63, 'ru', 'Ваш аккаунт заблокирован.'),
(64, 'ru', 'Неверный пароль.'),
(65, 'ru', 'Электронная почта'),
(66, 'ru', 'Проверочный код'),
(67, 'ru', 'Старый пароль'),
(68, 'ru', 'Неправильный старый пароль'),
(69, 'ru', 'Подтверждение пароля'),
(70, 'ru', 'Пароли не совпадают.'),
(71, 'ru', 'Минимальная длина пароля 4 символа.'),
(72, 'ru', 'Длина имени пользователя от 3 до 20 символов.'),
(73, 'ru', 'В имени пользователя допускаются только латинские буквы и цифры.'),
(74, 'ru', 'В название переменной допускаются только латинские буквы, цифры и символ подчеркивания.'),
(75, 'ru', '&quot;Длинна '' + n + '' должна быть не меньше ''+min+'' и не более ''+max+'' символов.&quot;'),
(76, 'ru', 'Пожалуйста, введите буквы, показанные на картинке выше.'),
(77, 'ru', 'Регистр значение не имеет.'),
(78, 'ru', 'Минимальная длина пароля 4 символа.'),
(79, 'ru', 'Забыли пароль?'),
(80, 'ru', 'Профиль'),
(81, 'ru', 'Ключ активации'),
(82, 'ru', 'Активация пользователя'),
(83, 'ru', 'Ваша учетная запись уже активирована.'),
(84, 'ru', 'Ваша учетная запись активирована.'),
(85, 'ru', 'еправильная ссылка активации учетной записи.'),
(86, 'ru', 'Дата регистрации'),
(87, 'ru', 'Последний визит'),
(88, 'ru', 'Суперпользователь'),
(89, 'ru', 'Статус'),
(90, 'ru', 'Роль'),
(91, 'ru', 'Хорошо'),
(92, 'ru', 'Показать все'),
(93, 'ru', 'Сохранить'),
(94, 'ru', 'Отмена'),
(95, 'ru', 'Новый пароль сохранен.'),
(96, 'ru', 'Изменить пароль'),
(97, 'ru', 'Ваш профиль'),
(98, 'ru', 'Регистрация завершена. Пожалуйста проверьте свой электронный ящик или выполните вход.'),
(99, 'ru', 'Регистрация завершена. Пожалуйста проверьте свой электронный ящик.'),
(100, 'ru', 'На Ваш адрес электронной почты было отправлено письмо с инструкциями.'),
(101, 'ru', 'Thank you for your registration. Please tbl_login.'),
(102, 'ru', 'Регистрация завершена. Пожалуйста свяжитесь с администрацией сайта для активации аккаунта.'),
(103, 'ru', 'Восстановить'),
(104, 'ru', 'Пожалуйста, введите Ваш логин или адрес электронной почты.'),
(105, 'ru', 'Неправильная ссылка востановления пароля.'),
(106, 'ru', 'Уже существует.'),
(107, 'ru', 'Имя'),
(108, 'ru', 'Фамилия'),
(109, 'ru', 'email'),
(110, 'ru', 'Создать системного пользователя'),
(111, 'ru', 'Системные пользователи'),
(112, 'ru', 'Да'),
(113, 'ru', 'Нет'),
(114, 'ru', 'Да и показать при регистрации'),
(115, 'ru', 'Нет, но показать при регистрации'),
(116, 'ru', 'Не активирован'),
(117, 'ru', 'Активирован'),
(118, 'ru', 'Суперадминистратор'),
(119, 'ru', 'Администратор'),
(120, 'ru', 'Модератор'),
(121, 'ru', 'Без роли'),
(122, 'ru', 'Управление системными пользователями'),
(123, 'ru', 'Обновить системного пользователя'),
(124, 'ru', 'Просмотреть системного пользователя'),
(125, 'ru', 'Заблокирован'),
(126, 'ru', 'Please fill out the following form with your login credentials:'),
(127, 'ru', 'Поля * обязательны'),
(128, 'ru', 'Список пользователей'),
(129, 'ru', 'Редактировать'),
(130, 'ru', 'Редактирование профиля'),
(131, 'ru', 'Новый'),
(132, 'ru', 'Создать'),
(133, 'ru', 'Управление'),
(134, 'ru', 'Управление пользователями'),
(135, 'ru', 'Пользователи'),
(136, 'ru', 'Править'),
(137, 'ru', 'Удалить'),
(138, 'ru', 'Удалить файл'),
(139, 'ru', 'Просмотр профиля'),
(140, 'ru', 'Вы действительно хотите удалить пользователя?'),
(141, 'ru', 'Изменения сохранены'),
(142, 'ru', 'Настройка полей'),
(143, 'ru', 'Имя переменной'),
(144, 'ru', 'Заголовок'),
(145, 'ru', 'Тип поля'),
(146, 'ru', 'Размер поля'),
(147, 'ru', 'Минимальный размер поля'),
(148, 'ru', 'обязательно'),
(149, 'ru', 'Совпадение'),
(150, 'ru', 'Диапазон'),
(151, 'ru', 'Сообщение об ошибке'),
(152, 'ru', 'Другой валидатор'),
(153, 'ru', 'JSON строка (пример: {example}).'),
(154, 'ru', 'По умолчанию'),
(155, 'ru', 'Позиция'),
(156, 'ru', 'Видимость'),
(157, 'ru', 'Зарегистрированные пользователи'),
(158, 'ru', 'Для всех'),
(159, 'ru', 'Только владелец'),
(160, 'ru', 'Скрыто'),
(161, 'ru', 'Поля профиля'),
(162, 'ru', 'Поле профиля #'),
(163, 'ru', 'Настройка полей'),
(164, 'ru', 'Создать профиль'),
(165, 'ru', NULL),
(166, 'ru', 'Просмотр профиля'),
(167, 'ru', 'Удалить профиль'),
(168, 'ru', 'Обновить профиль'),
(169, 'ru', 'Виджет'),
(170, 'ru', 'Параметры виджета'),
(171, 'ru', 'Название виджета.'),
(172, 'ru', 'Допускаются строчные буквы и цифры.'),
(173, 'ru', 'Название поля на языке &quot;sourceLanguage&quot;.'),
(174, 'ru', 'Тип поля колонки в базе данных.'),
(175, 'ru', 'Размер поля колонки в базе данных'),
(176, 'ru', 'Минимальное значение поля (проверка формы).'),
(177, 'ru', 'Обязательное поле (проверка формы).'),
(178, 'ru', 'Регулярные выражения (пример: ''/^[A-Za-z0-9s,]+$/u'')'),
(179, 'ru', 'Предопределенные значения (пример: 1;2;3;4;5 или 1==Один;2==Два;3==Три;4==Четыре;5==Пять).'),
(180, 'ru', 'Сообщение об ошибке при проверке формы.'),
(181, 'ru', 'Значение поля по умолчанию (база данных).'),
(182, 'ru', 'Порядок отображения полей.'),
(183, 'ru', 'Не входил'),
(184, 'ru', 'Искать'),
(185, 'ru', 'Расширенный поиск'),
(186, 'ru', 'Вы можете использовать операторы сравнения ( &lt;, &lt;=, &gt;, &gt;=, &lt;&gt; or = ) установив их перед значением.'),
(187, 'ru', 'Фотография'),
(188, 'ru', 'выбрать город'),
(189, 'ru', 'ВОЗМОЖНОСТИ'),
(190, 'ru', 'ПРАВИЛА'),
(191, 'ru', 'ВОПРОСЫ И ОТВЕТЫ'),
(192, 'ru', 'ЛОГИН'),
(193, 'ru', 'Далее'),
(194, 'ru', 'НОВЫЙ ЗАРЕГИСТРИРОВАВШИЙСЯ'),
(195, 'ru', 'ШАГ'),
(196, 'ru', 'Статические страницы'),
(197, 'ru', 'ТЕКУЩИЕ'),
(198, 'ru', 'РЕГИСТРАЦИИ'),
(199, 'ru', 'Выход'),
(200, 'ru', 'СТАТИСТИКА'),
(201, 'ru', 'СТРУКТУРА'),
(202, 'ru', 'НОВОСТИ'),
(203, 'ru', 'ЧАТ'),
(204, 'ru', 'ПРИГЛАШЕНИЕ'),
(205, 'ru', 'НАСТРОЙКИ'),
(206, 'ru', 'ПОМОЩЬ'),
(207, 'ru', 'РЕГИСТРАЦИЯ'),
(208, 'ru', 'Онлайн'),
(209, 'ru', 'Новости'),
(210, 'ru', 'Обратная связь'),
(211, 'ru', 'канал YouTube'),
(212, 'ru', 'О нас'),
(213, 'ru', 'О проекте'),
(214, 'ru', 'Наши партнеры'),
(215, 'ru', 'Связаться с нами и банковские реквизиты'),
(216, 'ru', 'Обслуживание'),
(217, 'ru', 'Финансовая помощь'),
(218, 'ru', 'Бизнес-машина'),
(219, 'ru', 'Совместная реклама'),
(220, 'ru', 'Личный сайт'),
(221, 'ru', 'SMS-рассылки'),
(222, 'ru', 'Правила'),
(223, 'ru', 'Соглашение об участии'),
(224, 'ru', ' принципы сообщества'),
(225, 'ru', 'Политика антиспама'),
(226, 'ru', 'Сотрудничество'),
(227, 'ru', 'Платежные системы'),
(228, 'ru', 'Обменники'),
(229, 'ru', 'Площади для рекламы'),
(230, 'ru', 'Стать реселлером'),
(231, 'ru', 'Техническая поддержка'),
(232, 'ru', 'Инструкции'),
(233, 'ru', 'Форум'),
(234, 'ru', 'Связаться с нами'),
(235, 'ru', 'Всемирная Благотворительная Система ООО JMWS ПОЛЬША'),
(236, 'ru', 'Личная структура учасника'),
(237, 'ru', 'Общаяструктура бизнесс клуба'),
(238, 'ru', 'Данные успешно сохранены'),
(239, 'ru', 'Финансы'),
(240, 'ru', 'Предложения'),
(241, 'ru', 'работа сайта'),
(242, 'ru', 'Добавить баннеры для админ-панели.'),
(243, 'ru', 'ЗАГРУЗИТЬ'),
(244, 'ru', 'ИНТЕРНЕТ-РЕКЛАМА'),
(245, 'ru', 'Ширина'),
(246, 'ru', 'Высота'),
(247, 'ru', 'НАСТРОЙКИ УЧЕТНОЙ ЗАПИСИ'),
(248, 'ru', 'ПОЛЬЗОВАТЕЛЬ'),
(249, 'ru', 'ИМЯ'),
(250, 'ru', 'ФАМИЛИЯ'),
(251, 'ru', 'ДАТА РОЖДЕНИЯ'),
(252, 'ru', 'ГОРОД'),
(253, 'ru', 'СТРАНА'),
(254, 'ru', 'показывать всем пользователям'),
(255, 'ru', 'VOIP/Мобильный'),
(256, 'ru', 'ТЕКУЩИЙ ПАРОЛЬ'),
(257, 'ru', 'НОВЫЙ ПАРОЛЬ'),
(258, 'ru', 'НОВЫЙ КОШЕЛЕК'),
(259, 'ru', 'МОЕ ВРЕМЯ'),
(260, 'ru', 'ЯЗЫК'),
(261, 'ru', 'РУССКИЙ'),
(262, 'ru', 'РУССКИЙ2'),
(263, 'ru', 'КОШЕЛЕК'),
(264, 'ru', 'ДЕТАЛИ ОПЛАТЫ'),
(265, 'ru', 'АВАТАР'),
(266, 'ru', 'ВЫБРАТЬ ФОТО'),
(267, 'ru', 'показать страну ко всеобщему использованию'),
(268, 'ru', 'показать город всем'),
(269, 'ru', 'показать скайп всем'),
(270, 'ru', 'показать email всем'),
(271, 'ru', 'Все поля требуются, кроме вашего профиля Skype и социальных сетей'),
(272, 'ru', 'Выбранное имя вашей учетной записи будет зарезервировано для вас, пока не станет активным'),
(273, 'ru', 'выбранное вами имя сохранится после деактивации в течение 30 дней'),
(274, 'ru', 'СОХРАНИТЬ'),
(275, 'ru', 'Ваш e-mail был изменен на'),
(276, 'ru', 'Вы подтвердили ваш email. Продолжите оставшиеся 4 шага.'),
(277, 'ru', 'ДАЛЕЕ'),
(278, 'ru', 'На вашу почту было отправлено письмо. В письме перейдите, пожалуйста, по ссылке'),
(279, 'ru', 'ЕСЛИ ВЫ НЕ ПОЛУЧИЛИ ПИСЬМО'),
(280, 'ru', 'Поздравляем! Вы стали полноправным участником системы'),
(281, 'ru', 'Чтобы активировать свой аккаунт, вы должны сделать взнос за участие в размере'),
(282, 'ru', 'Чтобы активировать свой аккаунт, вы должны сделать взнос за участие в размере'),
(283, 'ru', 'ВЗНОС $'),
(284, 'ru', 'Я согласен с правилами и принимаю условия'),
(285, 'ru', 'Сроки и условия'),
(286, 'ru', 'Поздравляем! Вы уже вошли в систему!'),
(287, 'ru', 'Теперь, чтобы стать участником бизнеса, вы должны пройти заключительный шаг.'),
(288, 'ru', 'Участие бизнеса позволит вам получить так много вещей и так много вещей! Не тратьте время!'),
(289, 'ru', 'ЗАРЕГИСТРИРОВАННЫЕ ЧЛЕНЫ'),
(290, 'ru', 'ТЕКУЩАЯ РЕГИСТРАЦИЯ'),
(291, 'ru', 'Ошибка'),
(292, 'ru', 'ПРИСОЕДИНИТЬСЯ'),
(293, 'ru', 'ЛИДЕРЫ'),
(294, 'ru', 'ВЫПЛАЧЕНО КОМИССИОННЫХ'),
(295, 'ru', 'ТЕКУЩИЕ ПЛАТЕЖИ'),
(296, 'ru', 'ОТДАНО НА БЛАГОТВОРИТЕЛЬНОСТЬ'),
(297, 'ru', 'ТЕКУЩИЕ ОТЧИСЛЕНИЯ'),
(298, 'ru', 'ВВЕДИТЕ КОД С КАРТИНКИ'),
(299, 'ru', 'ЗАБЫЛИ ПАРОЛЬ?'),
(300, 'ru', 'ПАРОЛЬ'),
(301, 'ru', 'Информация'),
(302, 'ru', 'Добавить в список'),
(303, 'ru', 'Отправить сообщение'),
(304, 'ru', 'Искать пользователей'),
(305, 'ru', 'Пользователь был успешно добавлен'),
(306, 'ru', 'Вы не можете добавить сами себя'),
(307, 'ru', 'Пользователь уже был добавлен'),
(308, 'ru', 'Пользователь успешно добавлен'),
(309, 'ru', 'Пользователь не найден'),
(310, 'ru', 'Пользователь не был добавлен'),
(311, 'ru', 'Кошелек отправителя или получателя отсутмствует'),
(312, 'ru', 'Чат'),
(313, 'ru', 'Города'),
(314, 'ru', 'Общая статистика'),
(315, 'ru', 'Всего'),
(316, 'ru', 'Сегодня'),
(317, 'ru', 'Вошли'),
(318, 'ru', 'Обороты'),
(319, 'ru', 'Активаций всего'),
(320, 'ru', 'Активаций сегодня'),
(321, 'ru', 'Капитал всего'),
(322, 'ru', 'Капитал сегодня'),
(323, 'ru', 'Благотоворительность'),
(324, 'ru', 'Всего передано'),
(325, 'ru', 'Посещения'),
(326, 'ru', 'Вчера'),
(327, 'ru', 'Месяц'),
(328, 'ru', 'месяц'),
(329, 'ru', 'день'),
(330, 'ru', 'час'),
(331, 'ru', 'с&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;'),
(332, 'ru', 'шаг&amp;nbsp;'),
(333, 'ru', 'по'),
(334, 'ru', 'отправить'),
(335, 'ru', 'Неправильный формат даты интервала'),
(336, 'ru', 'Нет данных для отображения'),
(337, 'ru', 'Версии маркетинг-плана'),
(338, 'ru', 'Менеджмент ЧАВО'),
(339, 'ru', 'Добавить'),
(340, 'ru', 'Приглашение'),
(341, 'ru', 'ай-ди'),
(342, 'ru', 'Ссылка на видео'),
(343, 'ru', 'Файл'),
(344, 'ru', 'Ссылка на файл'),
(345, 'ru', 'Создать '),
(346, 'ru', 'Создать приглашение'),
(347, 'ru', 'Просмотреть приглашение'),
(348, 'ru', 'Управление приглашениями'),
(349, 'ru', 'Маркетинг план'),
(350, 'ru', 'Установить текущей'),
(351, 'ru', 'Управление версиями маркетинг-плана'),
(352, 'ru', 'Описание'),
(353, 'ru', 'Дата создания'),
(354, 'ru', 'Активность'),
(355, 'ru', 'Создать версию'),
(356, 'ru', 'Просмотр версий маркетинг плана'),
(357, 'ru', '№'),
(358, 'ru', 'Просмотреть версии'),
(359, 'ru', 'Создать версию'),
(360, 'ru', 'Обновить версию'),
(361, 'ru', 'Удалить версию'),
(362, 'ru', 'Управление версиями'),
(363, 'ru', 'Операции'),
(364, 'ru', 'название'),
(365, 'ru', 'значение'),
(366, 'ru', 'Удалить'),
(367, 'ru', 'Создать новость'),
(368, 'ru', 'Управление новостью'),
(369, 'ru', 'Реквизиты'),
(370, 'ru', 'Обучение'),
(371, 'ru', 'Управление языками'),
(372, 'ru', '&lt;br&gt;Пустое поле пароля означает старый пароль&lt;br&gt;заполняйте это поле если хотите сменить старый пароль на новый.&lt;br&gt;&lt;br&gt;'),
(373, 'ru', 'Языки отсутствуют'),
(374, 'ru', 'Название языка для отображения'),
(375, 'ru', 'Этот язык уже присутствует'),
(376, 'ru', 'Новый язык добавлен успешно'),
(377, 'ru', 'Язык удален успешно'),
(378, 'ru', 'Редактирование завершено'),
(379, 'ru', 'Редактирование завершилось с ошибками'),
(380, 'ru', 'Русский'),
(381, 'ru', 'Общая статистика'),
(382, 'ru', 'Страны'),
(383, 'ru', 'Обновить новость'),
(384, 'ru', 'Список новостей'),
(385, 'ru', 'Просмотреть новость'),
(386, 'ru', 'Активировано'),
(387, 'ru', 'Загрузить изображение'),
(388, 'ru', 'Контент'),
(389, 'ru', 'Создать обучение'),
(390, 'ru', 'Управление обучениями'),
(391, 'ru', 'Изображение'),
(392, 'ru', 'Число'),
(393, 'ru', 'Дата'),
(394, 'ru', 'Управление ЧАВО'),
(395, 'ru', 'финансовые вопросы'),
(396, 'ru', 'вопросы производительности'),
(397, 'ru', 'другое'),
(398, 'ru', 'Вопрос'),
(399, 'ru', 'Ответ'),
(400, 'ru', 'Категория'),
(401, 'ru', 'Список ЧАВО'),
(402, 'ru', 'Создать ЧАВО'),
(403, 'ru', 'Обновить обучение'),
(404, 'ru', 'ЧАВО'),
(405, 'ru', 'Баннер'),
(406, 'ru', 'Текст'),
(407, 'ru', 'Добавить страну'),
(408, 'ru', 'Управление странами'),
(409, 'ru', 'Название'),
(410, 'ru', 'Код'),
(411, 'ru', 'Номер кода'),
(412, 'ru', 'Телефонный код'),
(413, 'ru', 'Список стран'),
(414, 'ru', 'Управление индексом'),
(415, 'ru', 'Управление городами'),
(416, 'ru', 'Создать город'),
(417, 'ru', 'Номер версии'),
(418, 'ru', 'Список слайдеров'),
(419, 'ru', 'лидер'),
(420, 'ru', 'Нотация'),
(421, 'ru', 'стоимость активации'),
(422, 'ru', 'стоимость старта'),
(423, 'ru', 'оплата на кошелек A'),
(424, 'ru', 'рендомно одному B1'),
(425, 'ru', 'рендомно одному B2'),
(426, 'ru', 'рендомно одному B3'),
(427, 'ru', 'выплата на кошелек F');



INSERT INTO SourceMessage (message) VALUES
('Registration payment'),
('Activation in system'),
('Entry into the business club'),
('You have become a business participant'),
('Changing the status of a business club'),
('ban period (in seconds)'),
('User ID'),
('Ban type'),
('Reason'),
('Author'),
('Importance'),
('From User'),
('From Purse'),
('To User'),
('To Purse'),
('Notation'),
('Amount'),
('Currency'),
('Tr Kind'),
('Tr Err Code'),
('Shortname'),
('An error occurred while blocking user'),
('Participant successfully blocked in chat'),
('The participant is successfully unlocked'),
('select'),
('Blocking'),
('Chat messages'),
('Participant is blocked'),
('Block participant'),
('Block'),
('Unlock'),
('Enter participant login'),
('Find and block participant'),
('Source language (English) is absent'),
('There is no russian message in message table! If it is need, you will switch off method RussianPatch in model LanguageInterphace->showTranslation'),
('No Versions'),
('Current version'),
('Period is set successfully'),
('Period begin'),
('Period end'),
('begin period for one week'),
('Loading image. Please wait'),
('Image uploaded successfully'),
('Registration is allowed only with a personal referral page'),
('Referral with the same name can not be found'),
('Confirmation of registration'),
('Unable to confirm your registration! The activation code is not found. Contact the site administrator'),
('Can not log in! Activation code is not valid. Contact the site administrator'),
('Your payment was successful'),
('Payment was successful'),
('An error occurred during the payment process. For details, contact the site administrator'),
('Question from FAQ'),
('Mail confirmation'),
('Business Club purse not set'),
('Failed to pay. Try again later'),
('Purse must have dollar prefix'),
('Sending mail error'),
('Code for login'),
('Your code for login'),
('Perfect Money service not available'),
('API Connection Wrong'),
('Perfect Money(...) Parameter choise not exists'),
('PerfectMoney(...) API in data must be an array and not empty'),
('Enter your Perfect Money data'),
('Raise status'),
('Click this button to login to the PerfectMoney site'),
('Account'),
('In order to be able to receive funds and make deposits, you must have a Perfect Money purse'),
('Enter your PM purse'),
('After you create your purse, put a number on this page'),
('Create purse');


INSERT INTO `Message` (`id`, `language`, `translation`) VALUES
(428, 'ru', 'Оплата регистрации'),
(429, 'ru', 'Активация в системе'),
(430, 'ru', 'Вступление в бизнес-клуб'),
(431, 'ru', 'Вы стали бизнес-участником'),
(432, 'ru', 'Изменение статуса в бизнес клубе'),
(433, 'ru', 'период бана (в секундах)'),
(434, 'ru', 'ИД юзера'),
(435, 'ru', 'Тип бана'),
(436, 'ru', 'Причина'),
(437, 'ru', 'Автор'),
(438, 'ru', 'Важность'),
(439, 'ru', 'От кого'),
(440, 'ru', 'Кошелек отправителя'),
(441, 'ru', 'Кому'),
(442, 'ru', 'Кошелек получателя'),
(443, 'ru', 'Примечание'),
(444, 'ru', 'Сумма'),
(445, 'ru', 'Валюта'),
(446, 'ru', 'Тип транзакции'),
(447, 'ru', 'Код ошибки'),
(448, 'ru', 'Короткое имя'),
(449, 'ru', 'Ошибка при блокировании юзера'),
(450, 'ru', 'Участник успешно заблокирован в чате'),
(451, 'ru', 'Участник успешно разблокирован'),
(452, 'ru', 'выбрать'),
(453, 'ru', 'Блокировка'),
(454, 'ru', 'Сообщения чата'),
(455, 'ru', 'Участник заблокирован'),
(456, 'ru', 'Заблокировать участника'),
(457, 'ru', 'Заблокировать'),
(458, 'ru', 'Разблокировать'),
(459, 'ru', 'Введите логин участника'),
(460, 'ru', 'Найти и заблокировать участника'),
(461, 'ru', 'Исходный язык (English) отсутствует'),
(462, 'ru', 'В таблице Message нет аналога матрицы на русском языке! Если это не нужно, выключите в модели LanguageInterphace->showTranslation метод RussianPatch'),
(463, 'ru', 'Нет версий'),
(464, 'ru', 'Текущая версия'),
(465, 'ru', 'Период задан успешно'),
(466, 'ru', 'Начало периода'),
(467, 'ru', 'Конец периода'),
(468, 'ru', 'начало периода для одной недели'),
(469, 'ru', 'Загружается изображение. Пожалуйста, подождите'),
(470, 'ru', 'Изображение успешно загружено'),
(471, 'ru', 'Регистрация разрешена только с личной страницы реферала'),
(472, 'ru', 'Не найден реферал с именем'),
(473, 'ru', 'Подтверждение регистрации'),
(474, 'ru', 'Не удается подтвердить регистрацию! Код активации не найден. Обратитесь к администратору сайта'),
(475, 'ru', 'Не удается авторизоваться! Код активации не правильный. Обратитесь к администратору сайта'),
(476, 'ru', 'Ваша оплата прошла успешно'),
(477, 'ru', 'Оплата произведена успешно'),
(478, 'ru', 'Произошла ошибка в процессе оплаты. Для подробностей обратитесь к администратору сайта'),
(479, 'ru', 'Вопрос от ЧАВО'),
(480, 'ru', 'Подтверждение почты'),
(481, 'ru', 'Не задан кошелек Бизнес Клуба'),
(482, 'ru', 'Оплата не прошла. Повторите операцию позже'),
(483, 'ru', 'Кошелек должен иметь долларовый префикс'),
(484, 'ru', 'Ошибка при отправке почты'),
(485, 'ru', 'Код для входа'),
(486, 'ru', 'Ваш код для входа'),
(487, 'ru', 'Сервис Perfect Money не доступен'),
(488, 'ru', 'Неверное соединение API'),
(489, 'ru', 'Perfect Money(...) Выбранный параметр не существует'),
(490, 'ru', 'PerfectMoney(...) входные данные API должны быть не пустым массивом'),
(491, 'ru', 'Введите данные из Perfect Money'),
(492, 'ru', 'Поднять статус'),
(493, 'ru', 'Нажмите эту кнопку для авторизации на сайте PerfectMoney'),
(494, 'ru', 'Аккаунт'),
(495, 'ru', 'Для того чтобы иметь возможность получать средства и пополнять счет вам необходимо иметь кошелек Perfect Money'),
(496, 'ru', 'Введите свой PM кошелек'),
(497, 'ru', 'После того как вы создадите свой кошелек, введите его номер на этой странице'),
(498, 'ru', 'Создать кошелек');

INSERT INTO SourceMessage (message) VALUES
('INCOME'),
('checks today'),
('Show part'),
('WITHDROAW FUNDS'),
('VISIT'),
('private in team'),
('In this month'),
('CHARITY'),
('VISITS'),
('private team today'),
('Business Club today'),
('Total in today'),
('Total income received');

INSERT INTO `Message` (`id`, `language`, `translation`) VALUES
(499, 'ru', 'ДОХОД'),
(500, 'ru', 'Чеки за сегодня'),
(501, 'ru', 'Показать часть'),
(502, 'ru', 'ВЫВЕСТИ СРЕДСТВА'),
(503, 'ru', 'ПОСЕЩЕНИЯ'),
(504, 'ru', 'Личный в команде'),
(505, 'ru', 'В этом месяце'),
(506, 'ru', 'БЛАГОТВОРИТЕЛЬНОСТЬ'),
(507, 'ru', 'ПОСЕЩЕНИЯ'),
(508, 'ru', 'Личная команда сегодня'),
(509, 'ru', 'Бизнес-Клуб сегодня'),
(510, 'ru', 'Всего за сегодня'),
(511, 'ru', 'Всего получен доход');

INSERT INTO SourceMessage (id, message) VALUES
(512, 'COMISSION'),
(513, 'DEDUCTIONS'),
(514, 'Leave the account and re-register'),
(515, 'tomorrow'),
(516, 'days'),
(517, 'month'),
(518, 'month'),
(519, 'year'),
(520, 'from the first'),
(521, 'show messages'),
(522, 'Details'),
(523, 'Agreement'),
(524, 'Marketing'),
(525, 'ONLINE'),
(526,'Superrefer Id'),
(527, 'select super referal'),
(528, 'Pw Supervisor'),
(529, 'Pw Admin'),
(530, 'Pw Moderator'),
(531, 'Purse Activation'),
(532, 'Purse Club'),
(533, 'Club Purse Login'),
(534, 'Club Purse Password'),
(535, 'Purse Investor'),
(536, 'Purse FDL');

INSERT INTO `Message` (`id`, `language`, `translation`) VALUES
(512, 'ru', 'КОМИССИОННЫЕ'),
(513, 'ru', 'ОТЧИСЛЕНИЯ'),
(514, 'ru', 'Выполните выход из учетной записи и перерегистрируйтесь'),
(515, 'ru', 'вчера'),
(516, 'ru', 'дней'),
(517, 'ru', 'месяца'),
(518, 'ru', 'месяцев'),
(519, 'ru', 'год'),
(520, 'ru', 'с самого начала'),
(521, 'ru', 'показать сообщения'),
(522, 'ru', 'Лицензионное соглашение'),
(523, 'ru', 'Соглашение'),
(524, 'ru', 'Маркетинг'),
(525, 'ru', 'ОНЛАЙН'),
(526, 'ru', 'id Суперреферера'),
(527, 'ru', 'выбрать суперреферера'),
(528, 'ru', 'Пароль суперфдминистратора'),
(529, 'ru', 'Пароль администратора'),
(530, 'ru', 'Пароль модератора'),
(531, 'ru', 'Кошелек Активации'),
(532, 'ru', 'Кошелек Клуба'),
(533, 'ru', 'Логин кошелька клуба'),
(534, 'ru', 'Пароль кошелька клуба'),
(535, 'ru', 'Кошелек инвестора'),
(536, 'ru', 'Кошелек благотворительности');





