<?php
class LangDefaultInstall {
    public static function install(){
        $items = array(
"Settings",
"select country",
"Hello!",
"Your account is activated, the system set up an office for you, as you are subscribed to the mailing list of all the news system",
"To go to the office, follow the link",
"enter",
"Login",
"and enter your login information",
"login",
"password",
"In order to proceedfollow the link",
"Do not remove this message until you finally registered.",
"This link is unique and will operate until you pass all registration steps",
"Best Regards",
"administration",
"Congratulations on your purchase Business Start! Registration is fully passed.",
"Now login information will be used only your email and password.",
"To confirm registration follow the link",
"Model Name",
"Lable field name",
"Empty item name",
"Profile model relation name",
"Participants",
"Unified database participants",
"Participants structure",
"BusinessClub structure",
"Domain",
"Tariff",
"Created",
"Firstname",
"Lastname",
"City",
"Country",
"Structure",
"Business Club",
"Referal",
"Checks",
"Time",
"Phone",
"Skype",
"Birthday",
"Gmt",
"Income",
"Transfer to the Fund",
"Activate",
"Deactivate",
"Blacklist",
"See structure",
"New Participant",
"Registration",
"Register",
"Logout",
"username",
"username or email",
"Remember me next time",
"Username is incorrect.",
"Email is incorrect.",
"This user's name already exists.",
"This user's email address already exists.",
"You registered from {site_name}",
"Please activate you account go to {activation_url}",
"You account is not activated.",
"You account is blocked.",
"Password is incorrect.",
"E-mail",
"Verification Code",
"Old Password",
"Old Password is incorrect.",
"Retype Password",
"Retype Password is incorrect.",
"Incorrect password (minimal length 4 symbols).",
"Incorrect username (length between 3 and 20 characters).",
"Incorrect symbols (A-z0-9).",
"Variable name may consist of a-z, 0-9, underscores, begin with a letter.",
"Length of ' + n + ' must be between '+min+' and '+max+'.",
"Please enter the letters as they are shown in the image above.",
"Letters are not case-sensitive.",
"Minimal password length 4 symbols.",
"Lost Password?",
"Profile",
"activation key",
"User activation",
"You account is active.",
"You account is activated.",
"Incorrect activation URL.",
"Registration date",
"Last visit",
"Superuser",
"Status",
"Roles",
"Ok",
"Show all",
"Save",
"Cancel",
"New password is saved.",
"Change password",
"Your profile",
"Thank you for your registration. Please check your email or login.",
"Thank you for your registration. Please check your email.",
"Please check your email. An instructions was sent to your email address.",
"Thank you for your registration. Please {{login}}.",
"Thank you for your registration. Contact Admin to activate your account.",
"Restore",
"Please enter your login or email addres.",
"Incorrect recovery link.",
"Already exists.",
"First Name",
"Last Name",
"Email",
"Create System User",
"System Users",
"No",
"Yes",
"Yes and show on registration form",
"No, but show on registration form",
"Not active",
"Active",
"Superadmin",
"Admin",
"Moderator",
"Without Role",
"Manage System Users",
"Update System User",
"View System User",
"Banned",
"Please fill out the following form with your login credentials:",
"Fields with * are required.",
"List User",
"Edit",
"Edit profile",
"Create User",
"Create",
"Manage",
"Manage Users",
"Users",
"Update User",
"Delete User",
"Delete file",
"View User",
"Are you sure to delete this item?",
"Changes is saved.",
"Manage Profile Field",
"Variable name",
"Title",
"Field Type",
"Field Size",
"Field Size min",
"Required",
"Match",
"Range",
"Error Message",
"Other Validator",
"JSON string (example: {example}).",
"Default",
"Position",
"Visible",
"Registered users",
"For all",
"Only owner",
"Hidden",
"Profile Fields",
"View Profile Field #",
"Manage Profile Fields",
"Create Profile Field",
"List Profile Field",
"View Profile Field",
"Delete Profile Field",
"Update Profile Field",
"Widget",
"Widget parametrs",
"Widget name.",
"Allowed lowercase letters and digits.",
'Field name on the language of "sourceLanguage".',
"Field type column in the database.",
"Field size column in the database.",
"The minimum value of the field (form validator).",
"Required field (form validator).",
"Regular expression (example: '/^[A-Za-z0-9\s,]+$/u').",
"Predefined values (example: 1;2;3;4;5 or 1==One;2==Two;3==Three;4==Four;5==Five).",
"Error message when you validate the form.",
"The value of the default field (database).",
"Display order of fields.",
"Not visited",
"Search",
"Advanced Search",
"You may optionally enter a comparison operator (<, <=, >, >=, <> or =) at the beginning of each of your search values to specify how the comparison should be done.",
"Photo",
"select city",
"OPPORTUNITIES",
"RULES",
"QUESTIONS AND ANSWERS",
"LOGIN",
"Next",
"NEW MEMBER REGISTRATION",
"STEP 1",
"STEP 2",
"STEP 3",
"STEP 4",
"Exit",
"STATISTICS",
"STRUCTURE",
"NEWS",
"CHAT",
"INVITATION",
"SETTINGS",
"HELP",
"SIGN UP",
"Live",
"News",
"Feedback",
"YouTube Channel",
"About Us",
"About the project",
"Our partners",
"Contact and Bank details",
"Service",
"Financial assistance",
"Business Machine",
"Joint advertising",
"Personal Website",
"SMS-mailing",
"Rules",
"Participation agreement",
"Community Guidelines",
"Anti-spam policy",
"Cooperation",
"Payment systems",
"Exchangers",
"Advertising platforms",
"Become a Reseller",
"Support service",
"Instructions",
"Forum",
"Contact us",
"World Charity System JMWS LLC POLAND",
"PERSONAL TEAM STRUCTURE",
"GLOBAL STRUCTURE OF BUSINESS CLUB",
"Data saved successfull",
"Finance",
"Offers",
"Site work",
"Add banners to admin panel.",
"DOWNLOAD",
"INTERNET ADVERTISING",
"Width: ",
"Height: ",
"ACCOUNT SETTINGS",
"USERNAME",
"NAME",
"SURNAME",
"DATE OF BIRTH",
"CITY",
"COUNTRY",
"allow to show to all users",
"VIBER / MOBILE",
"CURRENT PASSWORD",
"NEW PASSWORD",
"NEW PURSE",
"MY TIME",
"LANGUAGE",
"RUSSIAN",
"RUSSIAN2",
"YOUR PURSE",
"PAYMENT DETAILS",
"AVATAR",
"SELECT IMAGE",
"show country to everyone user",
"show city to everyone user",
"show skype to everyone user",
"show email to everyone user",
"All fields except your profile skype and social networks are required",
"The selected name of your account will be reserved for you until it is activated",
"But even up to 30 days after deactivation, yours choosen name will be fixed",
"SAVE",
"Your e-mail has been changed to",
"Thank you! You just confirmed your email address. CONTINUE passed all 4 steps.",
"NEXT",
"On your mail has been sent. In the letter you will find a link Click on it.",
"IF YOU DO NOT RECEIVE A LETTER",
"Congratulations! You became a full member of the system.",
"To activate your account, you must make the participation fee of $ ",
"ou will pass on website payment system to pay",
"PAY $ ",
"I agree with the rules and accept",
"Terms and conditions",
"Congratulations! You are already logged in!",
"Now, to become a party to a business, you must pass the final step.",
"Business participation will allow you to get so many things and so many things! Do not waste time!",
"REGISTERED MEMBERS",
"CURRENT REGISTRATION",
"Error",
"JOIN",
"LEADERS",
"FEE PAID",
"CURRENT PAYMENTS",
"GIVEN ON CHARITY",
"CURRENT fEES",
"ENTER THE CODE",
"FORGOT YOUR PASSWORD?",
"PASSWORD",
"Information",
"Add user to list",
"Send message",
"Find users",
"The User was added to list",
"You can't add yourself",
"The User has already been added",
"The User has been added successfuly",
"The User hasn't been found",
"The User hasn't been added",
"Recipient's or Sender's purse absent",
"Chat",
"Cities",
"General statistics",
"Total",
"Today",
"Entered",
"Money Turnover",
"Activations total",
"Activations today",
"Capital total",
"Capital today",
"Charity",
"Total transferred",
"Visits",
"Yesterday",
"Month",
"month",
"day",
"hour",
"from",
"step",
"to",
"send",
"invalid interval date format",
"No data for display",
"Mpversions",
"Faq Management",
"Add",
"Invitation",
"Id",
"Video Link",
"File",
"File Link",
"Create Invitation",
"Update Invitation",
"View Invitation",
"Manage Invitations",
"Marketings Plan",
"set current",
"Manage versions of marketings plan",
"Description",
"Creationdate",
"Activity",
"Create Version",
"View Mpversions",
"#",
"List Mpversions",
"Create Mpversions",
"Update Mpversions",
"Delete Mpversions",
"Manage Mpversions",
"Operations",
"name",
"value",
"Delete",
"Create News",
"Manage News",
"Requisites",
"Training",
        );
        $sql = 'INSERT INTO SourceMessage (message) VALUES ';
        foreach ($items as $one){
            if(strpos($one, '"') != FALSE){
                $sql .= "('".$one."'),";
            }else{
                $sql .= '("'.$one.'"),';
            }
        }
        $sql[strrpos($sql, ',')] = ';';
        Yii::app()->db->createCommand($sql)->execute();
    }
}
